import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build, context } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, "../src/index.tsx");
const distFile = join(here, "../dist/overlay.iife.js");
const generated = join(here, "../src/overlay-source.generated.ts");

const common = {
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  jsx: "automatic",
  jsxImportSource: "preact",
};

const watch = process.argv.includes("--watch");

if (watch) {
  // Dev: write the raw IIFE to dist/ on every change; the bridge (PIN_DEV) watches this file.
  mkdirSync(dirname(distFile), { recursive: true });
  const ctx = await context({ ...common, outfile: distFile, write: true });
  await ctx.watch();
  console.log("watching overlay ->", distFile);
} else {
  // Production: regenerate the .ts string embedded into bin/pinpoint.
  const result = await build({ ...common, write: false });
  const code = result.outputFiles[0].text;
  writeFileSync(
    generated,
    `// @generated by scripts/build-overlay.mjs — do not edit. Source: src/overlay/*.ts\n` +
      `export const OVERLAY_SOURCE = ${JSON.stringify(code)};\n`,
  );
  console.log("wrote", generated, `(${code.length} bytes)`);
}
