import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const result = await build({
  entryPoints: [join(here, "../src/overlay/index.tsx")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  write: false,
  jsx: "automatic",
  jsxImportSource: "preact",
});
const code = result.outputFiles[0].text;
const out = join(here, "../src/cdp/overlay-source.generated.ts");
writeFileSync(
  out,
  `// @generated by scripts/build-overlay.mjs — do not edit. Source: src/overlay/*.ts\n` +
    `export const OVERLAY_SOURCE = ${JSON.stringify(code)};\n`,
);
console.log("wrote", out, `(${code.length} bytes)`);
